### ISSUE TITLE
States are rated on datasets they might not have jurisdiction over

### ISSUE THREAD

**Issue by shua123** [opendata/Open-Data-Census#37]
Why are states judged on datasets that they may not have control over? Should a state/govt be marked down for not publishing data they don't own (or maybe even have)

**Comment by waldoj** [comment]
We tried to select datasets that all U.S. states have control over, either directly (they have gather that data themselves) or indirectly (they choose to delegate that power to localities). If you are aware of any states that do not have control over those datasets, because they are reserved by the federal government, that would be great to know about! (That may well be a problem with Washington D.C.)

**Comment by shua123** [comment]
I am not sure what you mean by "indirectly (they choose to delegate that power to localities)." 
For example, in Illinois, addresses are usually assigned by municipality (or county for unincorporated). What is the reasoning for grading Illinois on Address Points when the state government does not control addressing?

**Comment by waldoj** [comment]
Because whether or not they control addressing, they are in a position to collect addresses, as state GIOs do across the United States. In most (all?) states, addresses are assigned by localities, but they are then aggregated by the state, which needs to know where addresses are located across jurisdictional boundaries. Some states that aggregate that data choose to then republish it, including Virginia, Arkansas, Montana, Rhode Island, New Hampshire, and others that escape my mind just now. Many other states are in the process of doing the same. The US DOT has just launched an initiative to aggregate the data from state GIS systems so that they can provide a national repository.

Illinois quite likely aggregates local address data, but they do not choose to republish that data. But whether they choose not to aggregate it or they choose not to publish it isn't of this census' concern—the point is that they do not provide it, when they both could and should, as other states do.

**Comment by shua123** [comment]
So you are assuming data exists and then arbitrarily deciding what a state should republish (and the various ethically and logistical issues that come with that) while also ignoring the processes and functions of state agencies.

**Comment by waldoj** [comment]
That's right. It's a terrible project run by a buffoon. You shouldn't waste any time on it.
