### ISSUE TITLE
Missing Data: Texas Checkbook

### ISSUE THREAD

**Issue by SERutherford** [opendata/Open-Data-Census#74]
STATE: TX
DATASET: Checkbook
URL: http://www.texastransparency.org/Data_Center/Search_Datasets.php

Texas does provide bulk, downloadable TXT expenditure data by agency at the level of transactions. It's broken down on monthly basis. It's still quite a clumsy system.

**Comment by waldoj** [comment]
This is great, @SERutherford! About the best change that can be made—or discovered—about a given dataset is that it's available for download, instead of just viewing on screen. (And is consequently worth 40% of the score.) [This is updated on the site](https://census.usopendata.org/datasets.html?state=Texas&datatype=Checkbook), and Texas now gets a grade B instead of an F for their checkbook data. Thank you!
