### ISSUE TITLE
Missing Data:

### ISSUE THREAD

**Issue by DcJoeS** [opendata/Open-Data-Census#98]
STATE: MN
DATASET: Address Points
URL: https://gisdata.mn.gov/dataset/us-mn-state-metrogis-loc-address-points

DESCRIPTION/COMMENTS:

Currently this dataset contains points for Carver, Dakota and Ramsey counties. It will grow over time as more counties contribute data.

**Comment by waldoj** [comment]
Great! When I inventoried that dataset, I marked it as nonexistent because only 1 county was included. But the growth to 3 indicates that this is a real thing, and so it makes sense to score it accordingly. [That change has been made](https://census.usopendata.org/datasets.html?state=Minnesota), bringing Minnesota's score up from a 42% to 51%. I appreciate it!
